# Generated by Django 3.0.6 on 2020-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=20)),
                ('admin_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
