# Generated by Django 3.0.6 on 2020-09-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_cart1'),
    ]

    operations = [
        migrations.CreateModel(
            name='order1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('landmark', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.area1')),
                ('product_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.productAttributes1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.users')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='sales1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.order1')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='develiery_address_customer1',
            name='order_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='salesReturnDetails1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_return_date', models.DateField()),
                ('product_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.productAttributes1')),
            ],
            options={
                'db_table': 'sales_return_details',
            },
        ),
        migrations.CreateModel(
            name='salesReturn1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(null=True)),
                ('product_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.productAttributes1')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.sales1')),
            ],
            options={
                'db_table': 'sales_return',
            },
        ),
        migrations.CreateModel(
            name='rating1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('product_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.productAttributes1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.users')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='feedback1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('feedback_date', models.DateField()),
                ('product_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.productAttributes1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.users')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
