# Generated by Django 3.0.6 on 2020-09-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_auto_20200918_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order1',
            table='orders',
        ),
    ]
