# Generated by Django 3.0.6 on 2020-09-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_auto_20200918_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='product_attributes',
        ),
        migrations.AddField(
            model_name='order1',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.cart1'),
        ),
    ]
