# Generated by Django 3.0.6 on 2020-09-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_auto_20200918_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='cart',
        ),
        migrations.AddField(
            model_name='order1',
            name='product_attributes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.productAttributes1'),
        ),
        migrations.AddField(
            model_name='order1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.users'),
        ),
    ]
