# Generated by Django 3.0.6 on 2020-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_auto_20200920_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='order_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
