# Generated by Django 3.0.6 on 2020-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_remove_develiery_address_customer1_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
