# Generated by Django 3.0.6 on 2020-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_auto_20200922_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='flag',
            field=models.IntegerField(null=True),
        ),
    ]
