# Generated by Django 3.0.6 on 2020-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0014_order1_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
