# Generated by Django 3.0.6 on 2020-09-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0017_auto_20200924_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback1',
            name='product_attributes',
        ),
        migrations.RemoveField(
            model_name='rating1',
            name='product_attributes',
        ),
        migrations.AddField(
            model_name='feedback1',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.product1'),
        ),
        migrations.AddField(
            model_name='rating1',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.product1'),
        ),
    ]
