# Generated by Django 3.0.6 on 2020-10-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_auto_20200926_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='develiery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.develiery_address_customer1'),
        ),
    ]
