# Generated by Django 3.0.6 on 2020-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0020_auto_20201201_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee1',
            name='emp_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee1',
            name='emp_password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
